Repository micronaut-projects/micronaut-object-storage, pull requests merged in 2023-10, with the labels that each got.

#358 test: create blogContainer once
  object-storage-azure/src/test/groovy/io/micronaut/objectstorage/azure/AbstractAzureBlobStorageSpec.groovy
Labels: type: improvement

#359 doc: update Azure Contributing [ci skip]
  object-storage-azure/CONTRIBUTING.md
Labels: type: docs

#366 [object-storage] Update common files for branch master
  .editorconfig
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  buildSrc/build.gradle.kts
  buildSrc/src/main/groovy/io.micronaut.build.internal.objectstorage-example.gradle
  doc-examples/example-java/build.gradle.kts
  doc-examples/example-kotlin/build.gradle.kts
  gradle/libs.versions.toml
Labels: relates-to: build
