Repository micronaut-projects/micronaut-object-storage, pull requests merged in 2023-07, with the labels that each got.

#293 [object-storage] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#297 Object Storage to Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#299 Object Storage no milestones
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#304 [object-storage] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#313 rename ObjectStorageEnabledCondition to ToggeableCondition
  object-storage-aws/src/main/java/io/micronaut/objectstorage/aws/AwsS3Operations.java
  object-storage-azure/src/main/java/io/micronaut/objectstorage/azure/AzureBlobStorageEnabledCondition.java
  object-storage-azure/src/main/java/io/micronaut/objectstorage/azure/AzureBlobStorageFactory.java
  object-storage-azure/src/main/java/io/micronaut/objectstorage/azure/AzureBlobStorageOperations.java
  object-storage-core/src/main/java/io/micronaut/objectstorage/configuration/ToggeableCondition.java
  object-storage-gcp/src/main/java/io/micronaut/objectstorage/googlecloud/GoogleCloudStorageOperations.java
  object-storage-local/src/main/java/io/micronaut/objectstorage/local/LocalStorageOperations.java
  object-storage-oracle-cloud/src/main/java/io/micronaut/objectstorage/oraclecloud/OracleCloudStorageOperations.java
  object-storage-tck/src/main/groovy/io/micronaut/objectstorage/ObjectStorageConfigurationSpecification.groovy
Labels: type: improvement

#312 Fix local storage implementation when using keys containing directories
  object-storage-azure/src/test/groovy/io/micronaut/objectstorage/azure/AzureBlobStorageAzuriteSpec.groovy
  object-storage-local/src/main/java/io/micronaut/objectstorage/local/LocalStorageOperations.java
  object-storage-tck/src/main/groovy/io/micronaut/objectstorage/ObjectStorageOperationsSpecification.groovy
Labels: type: bug

#314 Make LocalStorageOperations the primary bean
  object-storage-local/build.gradle.kts
  object-storage-local/src/main/java/io/micronaut/objectstorage/local/LocalStorageOperations.java
  object-storage-local/src/test/groovy/io/micronaut/objectstorage/local/LocalStoragePrimarySpec.groovy
  src/main/docs/guide/local.adoc
Labels: type: improvement

#316 [object-storage] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#317 Fix for named bean injection
  object-storage-core/src/main/java/io/micronaut/objectstorage/configuration/ToggeableCondition.java
  object-storage-local/src/test/groovy/io/micronaut/objectstorage/local/LocalStorageNamedSpec.groovy
  object-storage-local/src/test/groovy/io/micronaut/objectstorage/local/LocalStoragePrimarySpec.groovy
Labels: type: bug

#321 [object-storage] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build
