Repository micronaut-projects/micronaut-object-storage, pull requests merged in 2024-11, with the labels that each got.

#542 [object-storage] Update common files for branch 2.6.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#544 Object Storage to Core 4.7.x
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#424 Add StreamingFileUploadRequest
  gradle/libs.versions.toml
  object-storage-azure/src/main/java/io/micronaut/objectstorage/azure/AzureBlobStorageOperations.java
  object-storage-core/build.gradle.kts
  object-storage-core/src/main/java/io/micronaut/objectstorage/request/StreamingFileUploadRequest.java
  object-storage-core/src/main/java/io/micronaut/objectstorage/request/UploadRequest.java
  object-storage-core/src/test/groovy/io/micronaut/objectstorage/request/StreamingFileUploadSpec.groovy
Labels: type: improvement
